In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 37.4 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
import pandas as pd
messages = pd.read_csv('/content/sample_data/SMSSpamCollection', sep='\t', names=["label", "message"])

In [ ]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [ ]:
import re

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
  review = review.lower()
  review = review.split()

  review = [lemmatizer.lemmatize(word) for word in review]
  corpus.append(review)

In [ ]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, [], '645'], [0, [], ':) '], [0, [], ':-) :-)']]

In [ ]:
corpus

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free',
  'entry',
  'in',
  'a',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  't',
  'c',
  's',
  'apply',
  'over',
  's'],
 ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say'],
 ['nah',
  'i',
  'don',
  't',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  's',
  'been',
  'week',
  's',
  'now',
  'and',
  'no',
  'word',
  'back',
  'i',
  'd',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'a',
  'a',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'u',
  'r',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['i',
  'm',
  'gonna',
  'be',
  'home',
  'soon',
  'and',
  'i',
  'don',
  't',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  'k',
  'i',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'p',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'a',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  't',
  'c',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'a',
  'rw'],
 ['i',
  've',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'i',
  'promise',
  'i',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'a',
  'blessing',
  'at',
  'all',
  'time'],
 ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will'],
 ['xxxmobilemovieclub',
  'to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'xxxmobilemovieclub',
  'com',
  'n',
  'qjkgighjjgcbl'],
 ['oh', 'k', 'i', 'm', 'watching', 'here'],
 ['eh',
  'u',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'i',
  'did',
  'he',
  'v',
  'naughty',
  'make',
  'until',
  'i',
  'v',
  'wet'],
 ['fine',
  'if',
  'that',
  's',
  'the',
  'way',
  'u',
  'feel',
  'that',
  's',
  'the',
  'way',
  'it',
  'gota',
  'b'],
 ['england',
  'v',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'w',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['i',
  'm',
  'going',
  'to',
  'try',
  'for',
  'month',
  'ha',
  'ha',
  'only',
  'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'i',
  'finish',
  'my',
  'lunch',
  'then',
  'i',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'u',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'i',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'a',
  'slice',
  'i',
  'm',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'i',
  'm',
  'sick',
  'when',
  'i',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'a',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  's',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['i',
  'm',
  'back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'i',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  's',
  'room'],
 ['ahhh',
  'work',
  'i',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  's',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  's',
  'why',
  'x',
  'doesn',
  't',
  'want',
  'to',
  'live',
  'with',
  'u'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'v',
  'apologetic',
  'n',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  't',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['k', 'tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'a',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'i',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'i',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops',
  'i',
  'll',
  'let',
  'you',
  'know',
  'when',
  'my',
  'roommate',
  's',
  'done'],
 ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'],
 ['anything', 'lor', 'u', 'decide'],
 ['hello',
  'how',
  's',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'i',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'd',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'i',
  'm',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'i',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'a',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'i',
  'forget',
  'to',
  'tell',
  'you',
  'i',
  'want',
  'you',
  'i',
  'need',
  'you',
  'i',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'i',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'a',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'i',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'i',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 't', 'you', 'get', 'hep', 'b', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  't',
  'do',
  'it',
  'i',
  'could',
  'maybe',
  'ask',
  'around',
  'a',
  'bit'],
 ['u',
  'don',
  't',
  'know',
  'how',
  'stubborn',
  'i',
  'am',
  'i',
  'didn',
  't',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'i',
  'kept',
  'telling',
  'mark',
  'i',
  'm',
  'not',
  'a',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['a',
  'gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'a',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'a',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['k',
  'fyi',
  'x',
  'ha',
  'a',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  's',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'i',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'i',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'i',
  'wa',
  'doing',
  'the',
  'best',
  'i',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'i',
  'm',
  'sorry',
  'i',
  'didn',
  't',
  'and',
  'don',
  't',
  'have',
  'more',
  'to',
  'give',
  'i',
  'm',
  'sorry',
  'i',
  'offered',
  'i',
  'm',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'c',
  'suprman',
  'v',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'i', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'a',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'i',
  'can',
  't',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'a', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'i',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'i',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'v',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'i',
  'look',
  'nice'],
 ['a',
  'a',
  'valued',
  'customer',
  'i',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'a',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'u',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'a',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'shracomorsglsuplt',
  'l',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  's',
  'stuff'],
 ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['k', 'k', 'where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['u', 'can', 'call', 'me', 'now'],
 ['i', 'am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'i',
  'am',
  'a',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['i',
  'like',
  'you',
  'people',
  'very',
  'much',
  'but',
  'am',
  'very',
  'shy',
  'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'a',
  'job',
  'how',
  'much',
  'do',
  'ta',
  's',
  'earn',
  'there'],
 ['sorry', 'i', 'll', 'call', 'later'],
 ['k', 'did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['i',
  'call',
  'you',
  'later',
  'don',
  't',
  'have',
  'network',
  'if',
  'urgnt',
  'sm',
  'me'],
 ['for',
  'real',
  'when',
  'u',
  'getting',
  'on',
  'yo',
  'i',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'i',
  'm',
  'done',
  'i',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'i',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'i',
  'm',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'i',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['i', 'm', 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  't',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'a',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'i',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'i',
  'haven',
  't',
  'done',
  'any',
  'of',
  'y',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'u',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'u',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'a',
  'you',
  'have',
  'won',
  'a',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'i',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'e',
  'afternoon',
  'u',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'h',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt', 'u'],
 ['i',
  'see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'a',
  'bit',
  'of',
  'a',
  'run',
  'forgot',
  'that',
  'i',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'n',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for',
  'u'],
 ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  't',
  'text',
  'me',
  'anymore',
  'i',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'a',
  'long',
  'a',
  'it',
  'legal',
  'wen',
  'can',
  'i',
  'pick',
  'them',
  'up',
  'y',
  'u',
  'ave',
  'x',
  'am',
  'xx'],
 ['i',
  'm',
  'still',
  'looking',
  'for',
  'a',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'i',
  'didn',
  't',
  'mean',
  'to',
  'do',
  'that',
  'i',
  'guess',
  'once',
  'i',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'a',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'i', 'll', 'hit', 'you', 'up', 'when', 'i', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  't',
  'a',
  'minecraft',
  'server'],
 ['i',
  'know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'i',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'i', 'guess', 'he', 's', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['i',
  'm',
  'ok',
  'wif',
  'it',
  'co',
  'i',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'i',
  'scared',
  'u',
  'dun',
  'like',
  'mah',
  'co',
  'u',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'a',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'k',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'i',
  'm',
  'fine',
  'too',
  'juz',
  'tt',
  'i',
  'm',
  'eatin',
  'too',
  'much',
  'n',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['a',
  'i',
  'entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'b',
  'day',
  'bos',
  'i',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'a',
  'winner',
  'u',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'a',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'a',
  'live',
  'operator',
  'claim',
  'p',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  's',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
words = corpus

In [ ]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'u', 'oni'],
 ['free',
  'entry',
  'in',
  'a',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  't',
  'c',
  's',
  'apply',
  'over',
  's'],
 ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say'],
 ['nah',
  'i',
  'don',
  't',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  's',
  'been',
  'week',
  's',
  'now',
  'and',
  'no',
  'word',
  'back',
  'i',
  'd',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'a',
  'a',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'u',
  'r',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['i',
  'm',
  'gonna',
  'be',
  'home',
  'soon',
  'and',
  'i',
  'don',
  't',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  'k',
  'i',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'p',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'a',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  't',
  'c',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'a',
  'rw'],
 ['i',
  've',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'i',
  'promise',
  'i',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'a',
  'blessing',
  'at',
  'all',
  'time'],
 ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will'],
 ['xxxmobilemovieclub',
  'to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'xxxmobilemovieclub',
  'com',
  'n',
  'qjkgighjjgcbl'],
 ['oh', 'k', 'i', 'm', 'watching', 'here'],
 ['eh',
  'u',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'i',
  'did',
  'he',
  'v',
  'naughty',
  'make',
  'until',
  'i',
  'v',
  'wet'],
 ['fine',
  'if',
  'that',
  's',
  'the',
  'way',
  'u',
  'feel',
  'that',
  's',
  'the',
  'way',
  'it',
  'gota',
  'b'],
 ['england',
  'v',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'w',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['i',
  'm',
  'going',
  'to',
  'try',
  'for',
  'month',
  'ha',
  'ha',
  'only',
  'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'i',
  'finish',
  'my',
  'lunch',
  'then',
  'i',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'u',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'i',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'a',
  'slice',
  'i',
  'm',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'i',
  'm',
  'sick',
  'when',
  'i',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'a',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  's',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['i',
  'm',
  'back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'i',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  's',
  'room'],
 ['ahhh',
  'work',
  'i',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  's',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  's',
  'why',
  'x',
  'doesn',
  't',
  'want',
  'to',
  'live',
  'with',
  'u'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'v',
  'apologetic',
  'n',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  't',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['k', 'tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'a',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'i',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'i',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops',
  'i',
  'll',
  'let',
  'you',
  'know',
  'when',
  'my',
  'roommate',
  's',
  'done'],
 ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'],
 ['anything', 'lor', 'u', 'decide'],
 ['hello',
  'how',
  's',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'i',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'd',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'i',
  'm',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'i',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'a',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'i',
  'forget',
  'to',
  'tell',
  'you',
  'i',
  'want',
  'you',
  'i',
  'need',
  'you',
  'i',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'i',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'a',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'i',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'i',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 't', 'you', 'get', 'hep', 'b', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  't',
  'do',
  'it',
  'i',
  'could',
  'maybe',
  'ask',
  'around',
  'a',
  'bit'],
 ['u',
  'don',
  't',
  'know',
  'how',
  'stubborn',
  'i',
  'am',
  'i',
  'didn',
  't',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'i',
  'kept',
  'telling',
  'mark',
  'i',
  'm',
  'not',
  'a',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['a',
  'gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'a',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'a',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['k',
  'fyi',
  'x',
  'ha',
  'a',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  's',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'i',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'i',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'i',
  'wa',
  'doing',
  'the',
  'best',
  'i',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'i',
  'm',
  'sorry',
  'i',
  'didn',
  't',
  'and',
  'don',
  't',
  'have',
  'more',
  'to',
  'give',
  'i',
  'm',
  'sorry',
  'i',
  'offered',
  'i',
  'm',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'c',
  'suprman',
  'v',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'i', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'a',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'i',
  'can',
  't',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'a', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'i',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'i',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'v',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'i',
  'look',
  'nice'],
 ['a',
  'a',
  'valued',
  'customer',
  'i',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'a',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'u',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'a',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'shracomorsglsuplt',
  'l',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  's',
  'stuff'],
 ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['k', 'k', 'where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['u', 'can', 'call', 'me', 'now'],
 ['i', 'am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'i',
  'am',
  'a',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['i',
  'like',
  'you',
  'people',
  'very',
  'much',
  'but',
  'am',
  'very',
  'shy',
  'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'a',
  'job',
  'how',
  'much',
  'do',
  'ta',
  's',
  'earn',
  'there'],
 ['sorry', 'i', 'll', 'call', 'later'],
 ['k', 'did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['i',
  'call',
  'you',
  'later',
  'don',
  't',
  'have',
  'network',
  'if',
  'urgnt',
  'sm',
  'me'],
 ['for',
  'real',
  'when',
  'u',
  'getting',
  'on',
  'yo',
  'i',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'i',
  'm',
  'done',
  'i',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'i',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'i',
  'm',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'i',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['i', 'm', 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  't',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'a',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'i',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'i',
  'haven',
  't',
  'done',
  'any',
  'of',
  'y',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'u',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'u',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'a',
  'you',
  'have',
  'won',
  'a',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'i',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'e',
  'afternoon',
  'u',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'h',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt', 'u'],
 ['i',
  'see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'a',
  'bit',
  'of',
  'a',
  'run',
  'forgot',
  'that',
  'i',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'n',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for',
  'u'],
 ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  't',
  'text',
  'me',
  'anymore',
  'i',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'a',
  'long',
  'a',
  'it',
  'legal',
  'wen',
  'can',
  'i',
  'pick',
  'them',
  'up',
  'y',
  'u',
  'ave',
  'x',
  'am',
  'xx'],
 ['i',
  'm',
  'still',
  'looking',
  'for',
  'a',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['a',
  'per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'a',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'i',
  'didn',
  't',
  'mean',
  'to',
  'do',
  'that',
  'i',
  'guess',
  'once',
  'i',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'a',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'i', 'll', 'hit', 'you', 'up', 'when', 'i', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  't',
  'a',
  'minecraft',
  'server'],
 ['i',
  'know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'i',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'i', 'guess', 'he', 's', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['i',
  'm',
  'ok',
  'wif',
  'it',
  'co',
  'i',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'i',
  'scared',
  'u',
  'dun',
  'like',
  'mah',
  'co',
  'u',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'a',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'k',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'i',
  'm',
  'fine',
  'too',
  'juz',
  'tt',
  'i',
  'm',
  'eatin',
  'too',
  'much',
  'n',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['a',
  'i',
  'entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'b',
  'day',
  'bos',
  'i',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'a',
  'winner',
  'u',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'a',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'a',
  'live',
  'operator',
  'claim',
  'p',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  's',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',

In [ ]:
model = gensim.models.Word2Vec(words)

In [ ]:
model.wv.index_to_key

['i',
 'to',
 'you',
 'a',
 'the',
 'u',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 's',
 'that',
 'have',
 'on',
 't',
 'now',
 'are',
 'can',
 'm',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'p',
 'r',
 'one',
 'need',
 'txt',
 'today',
 'n',
 'by',
 'going',
 'c',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'k',
 'see',
 'still',
 'mobile',
 'take',
 'd',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'him',
 'number',
 'give',
 'b',
 'more',
 'too',
 'happy',
 'work',
 'friend',
 'wat',
 'had',
 'way',
 'yes',
 'www',
 've',
 'e',
 'should',
 'let',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'said',
 'ask',
 'win',
 'doing',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'why',
 'meet',
 'find',
 'them',
 'miss',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'x',
 'gud',
 'buy',
 'again',
 'w',
 'before',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'his',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'were',
 'next',
 'tonight',
 'off',
 'show',
 'which',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'down',
 'name',
 'lot',
 'v',
 'other',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'didn',
 'start',
 'holiday',
 'y',
 'class',
 'stuff',
 'talk',
 'line',
 'g',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'being',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'having',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'world',
 'than',
 'because',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'into',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'o',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'between',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'j',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'these',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'l',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'both',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'f',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 ...]

In [ ]:
model.corpus_count

5572

In [ ]:
model.epochs

5

In [ ]:
model.wv.similar_by_word('glad')

[('lol', 0.9946672320365906),
 ('again', 0.9945975542068481),
 ('kiss', 0.9945117235183716),
 ('care', 0.9944764971733093),
 ('look', 0.9944695830345154),
 ('ya', 0.9944353699684143),
 ('quite', 0.9944326877593994),
 ('sat', 0.994339644908905),
 ('heart', 0.9942746758460999),
 ('im', 0.9942744374275208)]

In [ ]:
model.wv['sunny']

array([-0.03309969,  0.03327296,  0.0032697 ,  0.01986375,  0.00907893,
       -0.09080564,  0.01825732,  0.1244048 , -0.05643477, -0.03170522,
       -0.02687795, -0.06914186, -0.02854577,  0.04401139,  0.00827257,
       -0.02545172, -0.00292188, -0.0467874 , -0.01609917, -0.09384841,
        0.01266007,  0.01225515,  0.03873297, -0.00463604, -0.00161414,
        0.0035686 , -0.02488291, -0.03104886, -0.0188093 , -0.00267098,
        0.06262212, -0.02187593,  0.03588479, -0.02297952, -0.02134901,
        0.07144345,  0.00769368, -0.04600387, -0.04576337, -0.07847963,
        0.02789225, -0.04941444, -0.02257165,  0.02551283,  0.04027172,
       -0.00994915, -0.02606929, -0.02592633,  0.01952123,  0.01671381,
        0.01325735, -0.0524575 , -0.02379094, -0.00710665, -0.01351177,
        0.01528734,  0.02098623, -0.01203772, -0.0390531 ,  0.0029062 ,
        0.0019686 , -0.00208389,  0.01294248, -0.02376323, -0.06622338,
        0.07370918,  0.03988275,  0.04710677, -0.08216139,  0.07115831,
       -0.02318305,  0.03303298,  0.04980661, -0.01032681,  0.05163063,
        0.02516759, -0.01218527, -0.00640425, -0.03725458,  0.01721716,
       -0.03220966,  0.01342846, -0.02848719,  0.05325989, -0.00039758,
       -0.00716734,  0.02285701,  0.0369703 ,  0.05722827, -0.01305494,
        0.05669605,  0.02518441,  0.02598972,  0.01749952,  0.09766766,
        0.04369912,  0.0286697 , -0.03268889,  0.0228459 , -0.00346956],
      dtype=float32)

In [ ]:
import numpy as np

In [ ]:
def avg_word2vec(doc):
  word_vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
  if len(word_vectors) == 0:
    return np.zeros(model.vector_size) # Return a zero vector if no words are found
  return np.mean(word_vectors, axis=0)

In [ ]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [ ]:
from tqdm import tqdm

In [ ]:
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 5572/5572 [00:01<00:00, 4433.22it/s]

In [ ]:
X

[array([-1.32351115e-01,  2.20141426e-01,  4.86202762e-02,  7.93087259e-02,
         2.89427559e-03, -4.96526837e-01,  1.65886626e-01,  7.49389470e-01,
        -3.46390307e-01, -1.74429566e-01, -1.02625243e-01, -4.13607091e-01,
        -1.11789405e-01,  2.19089046e-01, -8.86968523e-03, -1.75137877e-01,
         7.54272845e-03, -3.31788838e-01, -8.83273855e-02, -5.08116782e-01,
         8.07906166e-02,  5.84461056e-02,  1.76037788e-01, -7.94153139e-02,
        -8.13913494e-02, -3.32907103e-02, -1.60217345e-01, -1.32790446e-01,
        -1.66172951e-01, -6.89750630e-03,  3.71868372e-01, -1.63496897e-01,
         1.65761009e-01, -1.90074757e-01, -1.29662767e-01,  4.03324813e-01,
         9.12934169e-02, -2.43461773e-01, -2.50945181e-01, -4.97145325e-01,
         1.11046828e-01, -2.92216659e-01, -1.15772411e-01,  1.43091515e-01,
         2.19853461e-01, -9.42829102e-02, -1.66623875e-01, -1.02257669e-01,
         1.20654188e-01,  9.43152308e-02,  4.06502411e-02, -2.68586397e-01,
        -7.59200603e-02, -4.17698175e-02, -7.67215788e-02,  6.25147000e-02,
         1.00309789e-01, -7.27906525e-02, -2.41480127e-01,  1.02453111e-02,
         7.09501058e-02,  1.81104094e-02,  5.75306006e-02, -1.25000298e-01,
        -3.71853113e-01,  3.79785687e-01,  2.76294440e-01,  2.90290505e-01,
        -4.44449514e-01,  3.94686371e-01, -9.32483822e-02,  1.30704001e-01,
         3.42474043e-01, -1.23274252e-02,  2.56324857e-01,  1.66803181e-01,
        -3.13675143e-02, -5.56764901e-02, -2.83007056e-01,  5.79710938e-02,
        -1.64246067e-01,  3.63016166e-02, -1.98535353e-01,  3.32279444e-01,
        -4.81781512e-02,  1.45228201e-04,  7.47953877e-02,  2.46124148e-01,
         3.15074742e-01, -1.51165072e-02,  3.12237293e-01,  1.23399213e-01,
         1.00099407e-01,  8.08749795e-02,  5.26549399e-01,  2.88866639e-01,
         1.39509544e-01, -2.61647761e-01,  1.16951689e-01, -2.57537942e-02],
       dtype=float32),
 array([-0.13339944,  0.19544503,  0.06522571,  0.07972272, -0.01636761,
        -0.44627005,  0.14970013,  0.6742062 , -0.3265246 , -0.16059044,
        -0.11259254, -0.37177053, -0.09599963,  0.19348875, -0.00349075,
        -0.16290036, -0.00740684, -0.3191572 , -0.07793815, -0.46988058,
         0.08024256,  0.06391187,  0.16297497, -0.06703848, -0.09436814,
        -0.01912162, -0.16855541, -0.12133904, -0.16221315, -0.01190025,
         0.31964904, -0.13182193,  0.12415824, -0.16516447, -0.10771618,
         0.34687772,  0.08489288, -0.21255758, -0.22662635, -0.4366091 ,
         0.0872304 , -0.2558481 , -0.12778386,  0.12925598,  0.2117918 ,
        -0.08707167, -0.15313883, -0.07305481,  0.11927626,  0.08277176,
         0.0306942 , -0.27038342, -0.07627144, -0.05261879, -0.06323189,
         0.06194563,  0.07828657, -0.06044276, -0.22428282, -0.01764224,
         0.06351443,  0.00890566,  0.05887495, -0.11699027, -0.3311695 ,
         0.33773348,  0.26107916,  0.2741256 , -0.37242612,  0.34983045,
        -0.07033728,  0.12926741,  0.31424385, -0.01326793,  0.22870608,
         0.17967553, -0.02808289, -0.052625  , -0.24670649,  0.07311563,
        -0.14934507,  0.02638784, -0.16861312,  0.29931396, -0.03774719,
        -0.01946631,  0.06285481,  0.23089173,  0.30074483, -0.00983762,
         0.29474837,  0.12234052,  0.08332907,  0.08549087,  0.4924077 ,
         0.29259938,  0.11497581, -0.22478811,  0.08849792, -0.02346343],
       dtype=float32),
 array([-1.25807837e-01,  2.33666763e-01,  2.56018844e-02,  9.27428231e-02,
         4.00252780e-03, -5.21769583e-01,  1.78235263e-01,  8.11775863e-01,
        -3.70329738e-01, -1.79253638e-01, -1.13855265e-01, -4.38299626e-01,
        -1.32922232e-01,  2.44298995e-01, -2.63287183e-02, -1.88368350e-01,
         7.00186566e-03, -3.25406909e-01, -8.34012851e-02, -5.05539060e-01,
         9.39337239e-02,  3.66461426e-02,  1.62129179e-01, -5.29072769e-02,
        -6.19903542e-02, -3.63013297e-02, -1.51446745e-01, -1.33292332e-01,
        -1.48328707e-01,  2.16234177e-02,  4.01789218e-01, -2.10776269e-01,
         2.23583832e-01, -2.06166908e-01, -1.71270400e-01,  4.78863150e-01,
         1.42527536e-01, -2.49830827e-01, -2.76336342e-01, -5.24499238e-01,
         1.57311156e-01, -3.21511030e-01, -1.51002750e-01,  1.94049582e-01,
         2.25721955e-01, -8.52724835e-02, -1.53639317e-01, -1.41215116e-01,
         1.18619457e-01,  5.58232702e-02,  5.01843654e-02, -2.70552963e-01,
        -6.95115551e-02, -4.20977846e-02, -8.38725194e-02,  8.11721981e-02,
         1.10681817e-01, -6.85460195e-02, -2.49162614e-01,  3.25793065e-02,
         3.49173620e-02,  5.49663231e-02,  4.93933633e-02, -1.50380924e-01,
        -4.22631949e-01,  4.11486030e-01,  3.10631722e-01,  2.95037180e-01,
        -4.67094600e-01,  4.29890394e-01, -9.67081562e-02,  1.12684205e-01,
         3.53312284e-01,  6.13296917e-03,  2.71664470e-01,  1.52362213e-01,
        -5.83161600e-02, -5.80100827e-02, -3.12162429e-01,  8.14768225e-02,
        -1.75146103e-01,  1.73074342e-02, -1.72557935e-01,  3.28719497e-01,
        -9.04810056e-02,  4.14953157e-02,  1.10928155e-01,  2.46918291e-01,
         3.35195214e-01, -3.20523232e-02,  3.12253565e-01,  1.36378020e-01,
         1.19507760e-01,  7.71827400e-02,  5.30038297e-01,  2.72966176e-01,
         1.91815302e-01, -2.84615368e-01,  1.35183886e-01,  5.17529028e-04],
       dtype=float32),
 array([-0.19480005,  0.27094346,  0.08006026,  0.11557867, -0.02579395,
        -0.6287485 ,  0.21390657,  0.97735864, -0.45880002, -0.22648935,
        -0.16564102, -0.5346334 , -0.1425024 ,  0.28158075, -0.01107778,
        -0.22837028, -0.00403679, -0.4513875 , -0.10914743, -0.66939986,
         0.11035369,  0.09273069,  0.22842772, -0.09277123, -0.129407  ,
        -0.02858702, -0.23906383, -0.17296238, -0.22227025, -0.01101455,
         0.4562723 , -0.19155806,  0.18905655, -0.2327096 , -0.15119894,
         0.51132804,  0.13345504, -0.31569892, -0.33151403, -0.6240536 ,
         0.12347084, -0.3750608 , -0.17920013,  0.18562262,  0.2975979 ,
        -0.1206286 , -0.21470515, -0.11292167,  0.17384472,  0.11283644,
         0.04625048, -0.3829047 , -0.09890709, -0.07037319, -0.09388937,
         0.08838867,  0.12082368, -0.09378208, -0.32024464, -0.01491939,
         0.0861738 ,  0.02279154,  0.08056545, -0.17741688, -0.48491722,
         0.48997393,  0.37478817,  0.391034  , -0.54048634,  0.5033113 ,
        -0.09914356,  0.182326  ,  0.44723997, -0.01647509,  0.32901946,
         0.24240808, -0.03882632, -0.06410673, -0.35765392,  0.1060891 ,
        -0.21054876,  0.04299508, -0.23895359,  0.42524487, -0.05602573,
        -0.01983642,  0.09254993,  0.326412  ,  0.42820016, -0.01042407,
         0.42075562,  0.17284313,  0.12508458,  0.11883216,  0.70081776,
         0.4104311 ,  0.17464148, -0.33037192,  0.13323821, -0.02382161],
       dtype=float32),
 array([-0.1727743 ,  0.22593357,  0.07754894,  0.11804792, -0.03436599,
        -0.5418242 ,  0.1874138 ,  0.8310107 , -0.38818935, -0.19225626,
        -0.13292727, -0.47587085, -0.09777323,  0.2512192 ,  0.0119466 ,
        -0.191561  ,  0.00136691, -0.36956844, -0.09698831, -0.5936204 ,
         0.11062364,  0.08265629,  0.18905756, -0.06509314, -0.11887904,
        -0.01924733, -0.20812215, -0.13970418, -0.21012957, -0.0233725 ,
         0.3604093 , -0.16336007,  0.14931895, -0.20365167, -0.11866467,
         0.42218164,  0.10413314, -0.27142555, -0.28502014, -0.5220046 ,
         0.0880431 , -0.31243053, -0.1671962 ,  0.165081  ,  0.25122744,
        -0.1052231 , -0.19388755, -0.09264435,  0.16624655,  0.11027468,
         0.05678556, -0.3321983 , -0.08046247, -0.07128671, -0.07773721,
         0.08317333,  0.10462762, -0.06549867, -0.2787179 , -0.02279815,
         0.05375933,  0.00845961,  0.06838215, -0.14353995, -0.4108198 ,
         0.44279602,  0.3079925 ,  0.35497293, -0.45713133,  0.43131772,
        -0.06446796,  0.1679503 ,  0.39028016, -0.02054749,  0.2970714 ,
         0.22494006,  0.00421146, -0.04646266, -0.3016789 ,  0.07159892,
        -0.20979226,  0.04714962, -0.21053053,  0.3681087 , -0.05256589,
        -0.03347555,  0.08647948,  0.26913005,  0.37389287,  0.0096721 ,
         0.36960462,  0.14317623,  0.11433464,  0.11365349,  0.6164234 ,
         0.37222454,  0.15595743, -0.26703298,  0.08717638, -0.0215498 ],
       dtype=float32),
 array([-0.16290055,  0.24761695,  0.06301706,  0.10865068, -0.00340245,
        -0.5738683 ,  0.19466448,  0.8783833 , -0.41776457, -0.20105177,
        -0.13631195, -0.49359936, -0.12363967,  0.2602938 , -0.00126918,
        -0.20613639,  0.01252042, -0.38059375, -0.10192259, -0.6044624 ,
         0.10793447,  0.07279389,  0.20370884, -0.07734574, -0.0845186 ,
        -0.03293039, -0.20024434, -0.14534734, -0.20538644, -0.00644531,
         0.41268831, -0.1921996 ,  0.18779048, -0.23536886, -0.15422553,
         0.47682855,  0.10939613, -0.2890653 , -0.30167904, -0.57138485,
         0.12337594, -0.3430609 , -0.15807447,  0.17722893,  0.25292528,
        -0.10517596, -0.19790806, -0.1232083 ,  0.14847599,  0.10003719,
         0.06470871, -0.33407837, -0.0934229 , -0.06261724, -0.08686188,
         0.07973772,  0.10561751, -0.07270166, -0.2826801 ,  0.00416806,
         0.06245115,  0.01675715,  0.06811051, -0.1435531 , -0.43214947,
         0.45993584,  0.33050904,  0.36095563, -0.5114957 ,  0.461486  ,
        -0.09075447,  0.17118894,  0.40816224, -0.01498532,  0.30166617,
         0.20664723, -0.01938867, -0.06082201, -0.3225367 ,  0.07000767,
        -0.21772298,  0.0423881 , -0.22703177,  0.3856505 , -0.06815711,
        -0.01626408,  0.10533929,  0.28479233,  0.38114724, -0.01963386,
         0.37334147,  0.15454304,  0.12249312,  0.09880655,  0.6194651 ,
         0.35248405,  0.17418092, -0.28693372,  0.12404923, -0.02506987],
       dtype=float32),
 array([-0.17440358,  0.25182393,  0.06529776,  0.10879879, -0.00819403,
        -0.5911201 ,  0.20174873,  0.89979297, -0.42562893, -0.2106215 ,
        -0.13616209, -0.50324315, -0.12636273,  0.25824246,  0.00308526,
        -0.20853373,  0.01444466, -0.40306327, -0.10627831, -0.62547004,
         0.10075282,  0.0806466 ,  0.21454318, -0.08720664, -0.0914027 ,
        -0.04170163, -0.21497056, -0.15204532, -0.21275975, -0.01463701,
         0.4268557 , -0.19187091,  0.18022047, -0.23368199, -0.14922951,
         0.48247805,  0.1013565 , -0.30183762, -0.30902869, -0.5865182 ,
         0.12168378, -0.3513988 , -0.15922786,  0.17321575,  0.2596151 ,
        -0.11459805, -0.20929718, -0.11860066,  0.15423991,  0.11747078,
         0.07089322, -0.35106158, -0.09837256, -0.05774104, -0.09166994,
         0.08365578,  0.10558526, -0.07995604, -0.29019338, -0.00314037,
         0.06896169,  0.0104614 ,  0.0744593 , -0.14869153, -0.44453543,
         0.47276026,  0.33443063,  0.3679436 , -0.5278694 ,  0.46726686,
        -0.09681584,  0.18611121,  0.42384958, -0.01932544,  0.31668526,
         0.21588281, -0.01891924, -0.06629942, -0.32945997,  0.06950848,
        -0.22271791,  0.05366909, -0.24676912,  0.40142936, -0.05929799,
        -0.02849171,  0.09611456,  0.29419342,  0.39322877, -0.01921538,
         0.38584444,  0.1590458 ,  0.12586561,  0.10417145,  0.6470909 ,
         0.36555168,  0.1739874 , -0.28644323,  0.12395276, -0.03466289],
       dtype=float32),
 array([-0.12110974,  0.22173929,  0.01593031,  0.07753535,  0.01967498,
        -0.4788013 ,  0.16379486,  0.7343727 , -0.3440753 , -0.16973525,
        -0.10011707, -0.3959376 , -0.1211924 ,  0.21214555, -0.01740492,
        -0.17546058,  0.01940402, -0.30125365, -0.08498757, -0.46466774,
         0.0818788 ,  0.033587  ,  0.16994606, -0.05394114, -0.03755555,
        -0.03765978, -0.14097768, -0.12132926, -0.13930538,  0.01986459,
         0.3737125 , -0.191799  ,  0.1906353 , -0.20581529, -0.16384019,
         0.4316608 ,  0.10305489, -0.23996925, -0.25537762, -0.4794322 ,
         0.13260949, -0.29671502, -0.1236362 ,  0.16569291,  0.19335273,
        -0.08400164, -0.14873785, -0.13066395,  0.10006937,  0.05729797,
         0.06713158, -0.2582573 , -0.08574837, -0.03857007, -0.08676598,
         0.06544912,  0.09478773, -0.06039992, -0.21794303,  0.03445753,
         0.04404023,  0.03881301,  0.05621377, -0.12044247, -0.36786684,
         0.38230148,  0.28720415,  0.27877566, -0.45248714,  0.38632548,
        -0.09552756,  0.1215103 ,  0.3285895 , -0.00211392,  0.24977806,
         0.1435923 , -0.05295727, -0.04680855, -0.28873736,  0.05248065,
        -0.17377304,  0.03308367, -0.1803551 ,  0.32195473, -0.07175951,
         0.023984  ,  0.10708515,  0.22830981,  0.30284524, -0.05116411,
         0.28494105,  0.12887318,  0.10787255,  0.05575035,  0.48878732,
         0.24118502,  0.17355558, -0.243753  ,  0.13009079, -0.01305637],
       dtype=float32),
 array([-1.22392267e-01,  2.51243830e-01,  2.33098678e-02,  8.45556855e-02,
         9.95321479e-03, -5.28318286e-01,  1.88717082e-01,  8.30663025e-01,
        -3.86032820e-01, -1.94898963e-01, -1.08072713e-01, -4.46827650e-01,
        -1.38284221e-01,  2.47071519e-01, -2.32378580e-02, -1.91914856e-01,
         2.41272673e-02, -3.31963390e-01, -9.23879519e-02, -5.08727670e-01,
         1.02866158e-01,  2.89188940e-02,  1.75554141e-01, -5.63915633e-02,
        -5.56907021e-02, -3.51339579e-02, -1.47783116e-01, -1.32114813e-01,
        -1.38096124e-01,  4.05307263e-02,  4.09515291e-01, -2.24197596e-01,
         2.22265199e-01, -2.31719330e-01, -1.97355300e-01,  4.88373518e-01,
         1.44599691e-01, -2.53923714e-01, -2.88326770e-01, -5.24104238e-01,
         1.47634715e-01, -3.36514860e-01, -1.50138646e-01,  2.03178659e-01,
         2.27535650e-01, -7.36225471e-02, -1.43809795e-01, -1.61869019e-01,
         9.97072533e-02,  5.02882972e-02,  6.62190765e-02, -2.85321206e-01,
        -9.06328335e-02, -4.65588123e-02, -1.01520434e-01,  7.82821849e-02,
         1.11115560e-01, -5.85915260e-02, -2.51581609e-01,  3.47267315e-02,
         3.10362577e-02,  5.73622435e-02,  5.72634302e-02, -1.36112943e-01,
        -4.13452774e-01,  4.38626438e-01,  3.28489095e-01,  3.08180004e-01,
        -4.93902057e-01,  4.41463053e-01, -1.02883138e-01,  1.25312462e-01,
         3.76303494e-01,  2.57581007e-03,  2.71161497e-01,  1.51118711e-01,
        -6.38269335e-02, -4.37259749e-02, -3.23730409e-01,  7.64040947e-02,
        -1.95508406e-01,  3.23625617e-02, -1.79321930e-01,  3.50792497e-01,
        -7.58638009e-02,  4.41825725e-02,  1.27928883e-01,  2.53397346e-01,
         3.52766067e-01, -4.90657538e-02,  3.27967882e-01,  1.42521113e-01,
         1.16971120e-01,  6.79913834e-02,  5.50729275e-01,  2.76880801e-01,
         2.12849110e-01, -2.77400017e-01,  1.40202358e-01, -2.78495078e-04],
       dtype=float32),
 array([-0.13788575,  0.28248823,  0.00609084,  0.09772979,  0.01179989,
        -0.6249549 ,  0.21364766,  0.94455254, -0.43429962, -0.21550716,
        -0.1248551 , -0.49911988, -0.1672949 ,  0.27959055, -0.04453221,
        -0.22270368,  0.01809956, -0.37822935, -0.10215835, -0.57731456,
         0.10753323,  0.02254162,  0.20679758, -0.06499469, -0.04953788,
        -0.0448319 , -0.17105171, -0.15195933, -0.16221946,  0.04183311,
         0.4912681 , -0.2556608 ,  0.280782  , -0.25923094, -0.22003634,
         0.56309664,  0.15615503, -0.2937713 , -0.31600183, -0.62152433,
         0.19446394, -0.38060763, -0.16207352,  0.23574005,  0.25316727,
        -0.10246106, -0.17155725, -0.18003045,  0.12530012,  0.06576309,
         0.06721575, -0.30721202, -0.08565912, -0.04192279, -0.10784148,
         0.09041943,  0.13042177, -0.08256222, -0.28321263,  0.05906539,
         0.04729244,  0.05610243,  0.06140084, -0.16437273, -0.48499367,
         0.48620605,  0.36900923,  0.33436656, -0.57878083,  0.50015205,
        -0.13133077,  0.13046318,  0.41866773,  0.00751504,  0.31458396,
         0.17690048, -0.08133859, -0.07104358, -0.36582407,  0.0870631 ,
        -0.20611095,  0.02710985, -0.20991221,  0.3955377 , -0.11113998,
         0.05561868,  0.14583586,  0.2879602 ,  0.3830709 , -0.05468735,
         0.3558161 ,  0.15818526,  0.13976927,  0.06805661,  0.6008824 ,
         0.28514737,  0.23126821, -0.32432505,  0.18559818, -0.00270455],
       dtype=float32),
 array([-0.17009225,  0.24931037,  0.09078539,  0.11535046, -0.03182012,
        -0.5774119 ,  0.20111038,  0.8721776 , -0.41431385, -0.20227416,
        -0.1309973 , -0.5005103 , -0.10377783,  0.25687343,  0.01733568,
        -0.19813468,  0.00733805, -0.38842624, -0.10995658, -0.6360824 ,
         0.12289452,  0.08673372,  0.20913176, -0.07464325, -0.12687668,
        -0.01786719, -0.21286264, -0.14809409, -0.22319584, -0.01980273,
         0.38400975, -0.1672181 ,  0.15927531, -0.22836901, -0.12422554,
         0.43465   ,  0.10190265, -0.2867013 , -0.29687226, -0.5541019 ,
         0.08061606, -0.3307358 , -0.16660705,  0.1684346 ,  0.26504084,
        -0.11237417, -0.20397829, -0.09883427,  0.17091307,  0.12001043,
         0.05794929, -0.350001  , -0.09130865, -0.07226708, -0.07528624,
         0.07949331,  0.10808288, -0.05996818, -0.29068565, -0.01541099,
         0.06012162, -0.00461869,  0.06690285, -0.1425825 , -0.41555396,
         0.47141656,  0.32132885,  0.3718404 , -0.5003934 ,  0.45343482,
        -0.07506618,  0.18486203,  0.4188549 , -0.02783486,  0.30758178,
         0.23668842,  0.00790603, -0.05011932, -0.3128366 ,  0.0667315 ,
        -0.22563837,  0.05525553, -0.23147969,  0.39319268, -0.0484324 ,
        -0.04361676,  0.09650875,  0.29262853,  0.39353448,  0.01181145,
         0.3915458 ,  0.15261735,  0.11958849,  0.11581988,  0.6509728 ,
         0.385107  ,  0.15625574, -0.276179  ,  0.10118916, -0.02703217],
       dtype=float32),
 array([-0.13093476,  0.26603594,  0.02080465,  0.09517971,  0.0194932 ,
        -0.58180416,  0.19521935,  0.9075713 , -0.42301244, -0.19591837,
        -0.12412346, -0.47937113, -0.16037486,  0.26559535, -0.03741789,
        -0.204156  ,  0.01109287, -0.3580755 , -0.08265927, -0.54993576,
         0.09497453,  0.03348127,  0.18150698, -0.06595123, -0.05234656,
        -0.04495443, -0.16302669, -0.14164817, -0.14314911,  0.03848236,
         0.45554507, -0.24669148,  0.27169898, -0.24290232, -0.2079817 ,
         0.55286324,  0.16835207, -0.28047657, -0.3089121 , -0.58683395,
         0.18186754, -0.36207333, -0.16250986,  0.22806704,  0.25306457,
        -0.07913712, -0.15867795, -0.17477241,  0.10701063,  0.04256573,
         0.05894734, -0.2831212 , -0.09129032, -0.03182919, -0.1000923 ,
         0.07737096,  0.12413524, -0.07312196, -0.26858762,  0.05508513,
         0.03065816,  0.07167001,  0.04904648, -0.16674827, -0.47081655,
         0.4547635 ,  0.35581285,  0.3153949 , -0.5263375 ,  0.4810531 ,
        -0.12183846,  0.12075226,  0.39052814,  0.01823951,  0.30210197,
         0.15366828, -0.0827778 , -0.07027917, -0.35800847,  0.09739552,
        -0.19612835,  0.01744083, -0.18047045,  0.35866117, -0.1002159 ,
         0.06112688,  0.13645662,  0.28250542,  0.37247437, -0.04997366,
         0.33825293,  0.15419136,  0.12905043,  0.06850539,  0.5802001 ,
         0.28734484,  0.2229141 , -0.3185504 ,  0.16460934,  0.00493673],
       dtype=float32),
 array([-0.154778  ,  0.2784589 ,  0.02060613,  0.11442886,  0.00472327,
        -0.6112604 ,  0.21402349,  0.95969623, -0.44240388, -0.21538651,
        -0.13562249, -0.5130726 , -0.15853423,  0.29023138, -0.03084156,
        -0.23139551,  0.01439698, -0.38349065, -0.1070264 , -0.59034556,
         0.11327212,  0.03466401,  0.19668458, -0.05729344, -0.07142325,
        -0.04421652, -0.17633013, -0.15332463, -0.16992864,  0.04086303,
         0.46860483, -0.25831404,  0.2622886 , -0.24993153, -0.21764416,
         0.56651163,  0.16781448, -0.29520854, -0.33353937, -0.61257654,
         0.17753315, -0.38512877, -0.18348682,  0.23750958,  0.26394764,
        -0.09587441, -0.17717028, -0.17976667,  0.12907821,  0.05550359,
         0.06943743, -0.33062196, -0.0966275 , -0.05568333, -0.1061411 ,

In [ ]:
len(X)

5572

In [ ]:
X_new = np.array(X)

In [ ]:
X_new.shape

(5572, 100)

In [ ]:
X_new[0].shape

(100,)

In [ ]:
y = pd.get_dummies(messages['label'])

In [ ]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [ ]:
y = y.iloc[:, 0].values

In [ ]:
y

array([ True,  True, False, ...,  True,  True,  True])

In [ ]:
messages.shape

(5572, 2)

In [ ]:
y.shape

(5572,)

In [ ]:
X[0].shape

(100,)

In [ ]:
X[0].reshape(1, -1).shape

(1, 100)

In [ ]:
df_rows = []
for i in range(0, len(X)):
  df_rows.append(pd.DataFrame(X[i].reshape(1, -1)))
df = pd.concat(df_rows, ignore_index=True)

In [ ]:
df.shape

(5572, 100)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.132351,0.220141,0.048620,0.079309,0.002894,-0.496527,0.165887,0.749389,-0.346390,-0.174430,...,0.312237,0.123399,0.100099,0.080875,0.526549,0.288867,0.139510,-0.261648,0.116952,-0.025754
1,-0.133399,0.195445,0.065226,0.079723,-0.016368,-0.446270,0.149700,0.674206,-0.326525,-0.160590,...,0.294748,0.122341,0.083329,0.085491,0.492408,0.292599,0.114976,-0.224788,0.088498,-0.023463
2,-0.125808,0.233667,0.025602,0.092743,0.004003,-0.521770,0.178235,0.811776,-0.370330,-0.179254,...,0.312254,0.136378,0.119508,0.077183,0.530038,0.272966,0.191815,-0.284615,0.135184,0.000518
3,-0.194800,0.270943,0.080060,0.115579,-0.025794,-0.628748,0.213907,0.977359,-0.458800,-0.226489,...,0.420756,0.172843,0.125085,0.118832,0.700818,0.410431,0.174641,-0.330372,0.133238,-0.023822
4,-0.172774,0.225934,0.077549,0.118048,-0.034366,-0.541824,0.187414,0.831011,-0.388189,-0.192256,...,0.369605,0.143176,0.114335,0.113653,0.616423,0.372225,0.155957,-0.267033,0.087176,-0.021550

In [ ]:
df['Output'] = y

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.132351,0.220141,0.048620,0.079309,0.002894,-0.496527,0.165887,0.749389,-0.346390,-0.174430,...,0.123399,0.100099,0.080875,0.526549,0.288867,0.139510,-0.261648,0.116952,-0.025754,True
1,-0.133399,0.195445,0.065226,0.079723,-0.016368,-0.446270,0.149700,0.674206,-0.326525,-0.160590,...,0.122341,0.083329,0.085491,0.492408,0.292599,0.114976,-0.224788,0.088498,-0.023463,True
2,-0.125808,0.233667,0.025602,0.092743,0.004003,-0.521770,0.178235,0.811776,-0.370330,-0.179254,...,0.136378,0.119508,0.077183,0.530038,0.272966,0.191815,-0.284615,0.135184,0.000518,False
3,-0.194800,0.270943,0.080060,0.115579,-0.025794,-0.628748,0.213907,0.977359,-0.458800,-0.226489,...,0.172843,0.125085,0.118832,0.700818,0.410431,0.174641,-0.330372,0.133238,-0.023822,True
4,-0.172774,0.225934,0.077549,0.118048,-0.034366,-0.541824,0.187414,0.831011,-0.388189,-0.192256,...,0.143176,0.114335,0.113653,0.616423,0.372225,0.155957,-0.267033,0.087176,-0.021550,True

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [ ]:
X = df.iloc[:,:100]

In [ ]:
y=df['Output']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
1919,-0.213660,0.276562,0.051023,0.134854,0.029651,-0.662731,0.220858,1.030506,-0.486262,-0.250341,...,0.428501,0.199075,0.159780,0.130787,0.742061,0.407105,0.176023,-0.327867,0.155536,-0.051297
4662,-0.138050,0.223415,0.054134,0.085924,0.001676,-0.525466,0.167787,0.778276,-0.362367,-0.180370,...,0.330927,0.121227,0.099451,0.093753,0.536228,0.304812,0.132193,-0.273470,0.115637,-0.030916
4022,-0.185838,0.259725,0.059016,0.123445,-0.002020,-0.630201,0.219289,0.969217,-0.462504,-0.229666,...,0.421069,0.177996,0.139723,0.114257,0.689390,0.404862,0.208252,-0.313322,0.125077,-0.024982
196,-0.155690,0.233313,0.046006,0.094686,0.013548,-0.517832,0.178652,0.808474,-0.378707,-0.192802,...,0.323046,0.142198,0.117553,0.081426,0.570421,0.307248,0.167867,-0.263430,0.133699,-0.024936
5242,-0.101712,0.153023,0.052595,0.065472,-0.017859,-0.359431,0.115704,0.541696,-0.247808,-0.118175,...,0.238884,0.084911,0.071327,0.068148,0.390406,0.228600,0.090620,-0.180725,0.076179,-0.012753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4011,-0.141825,0.261369,0.036289,0.100890,-0.004016,-0.579554,0.200927,0.897169,-0.421597,-0.203627,...,0.358540,0.152986,0.123464,0.081692,0.603565,0.313218,0.205718,-0.303803,0.148635,-0.002169
5309,-0.156475,0.245771,0.055506,0.097113,0.001015,-0.559891,0.189231,0.858615,-0.401398,-0.201378,...,0.360817,0.152466,0.124892,0.090276,0.602772,0.330334,0.170300,-0.281298,0.131908,-0.032623
5172,-0.171669,0.258782,0.078671,0.111330,-0.020213,-0.614406,0.205109,0.928166,-0.447054,-0.213748,...,0.413729,0.167788,0.122743,0.115872,0.670982,0.388088,0.176464,-0.295647,0.115856,-0.022277
2809,-0.148415,0.213417,0.069581,0.103449,-0.021553,-0.495656,0.169761,0.758781,-0.369765,-0.169412,...,0.330636,0.139321,0.105510,0.091356,0.559886,0.323249,0.146852,-0.224644,0.090494,-0.016160
1846,-0.154379,0.251330,0.062483,0.097223,-0.012794,-0.573780,0.197595,0.872513,-0.415777,-0.207659,...,0.373709,0.155869,0.112953,0.097073,0.616621,0.345379,0.174682,-0.285836,0.122983,-0.017367

In [ ]:
y_train

1919     True
4662     True
4022     True
196      True
5242     True
        ...
4011    False
5309     True
5172     True
2809     True
1846     True
Name: Output, Length: 4457, dtype: bool

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier = RandomForestClassifier()

In [ ]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score(y_test, y_pred)

0.967713004484305

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.92      0.84      0.88       153
        True       0.97      0.99      0.98       962

    accuracy                           0.97      1115
   macro avg       0.95      0.91      0.93      1115
weighted avg       0.97      0.97      0.97      1115